package com.a2z.enums;

public enum AdCategory {
    FURNITURE, ELECTRONICS, VEHICLES, REAL_ESTATE, SERVICES, JOBS, PERSONAL_ITEMS, HARDWARE, CLOTHING, TOYS,
    SPORTS_EQUIPMENT, BOOKS, MUSIC_INSTRUMENTS, PETS,GYM_EQUIPMENT,COSMETICS,MEDICINE, OTHER
}
